export const initialValues = {
  applicantName: "",
  wifeName: "",
  husbandIdCard: null,
  wifeIdCard: null,
  applicantDob: "",
  marriageDate: "",
  wifeDob: "",
  fatherHusbandName: "",
  gotra: "",
  resAddress: "",
  villageCity: "",
  district: "",
  state: "",
  pincode: "",
  telephone: "",
  mobileSelf: "",
  mobileWife: "",
  faxEmail: "",
  occupation: "",
  origin: "",
  corpusFund: "",
  lifeMagazineFee: "",
  membershipFee: "",
  husbandPhoto: null,
  wifePhoto: null,
};
